version: '3'

services:
  web:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    networks:
      gitlab-network:
        aliases:
          - gitlab.example.com

  runner:
    container_name: gitlab-runner
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab-network

  mail:
    container_name: mail-server
    image: 'tianon/exim4'
    hostname: mail.gitlab.example.com
    networks:
      - gitlab-network
    volumes:
      - './mailname:/etc/mailname:ro'

networks:
  gitlab-network:
    driver: bridge
